name: appsmith-cd  # Workflow name

on:
  push:
    branches:
      - release  # Trigger on push to master branch

jobs:
  deploy-appsmith2:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - run: "curl --location --fail-early --request POST https://ee-4861.dp.appsmith.com/api/v1/git/deploy/app/66b9c884c93b9d1752e250b7?branchName=release --header 'Authorization: Bearer ${{ secrets.APPSMITH_CD_KEY }}'"
